import { NodeDefinition, EdgeDefinition } from "../";

enum CATEGORIES {
  coding = "Coding / Coded elements",
  variant = "Genomic variant",
  noncoding = "Non-coding elements",
  process = "Pathway",
  ontology = "Ontology term",
  threeD = "3d genome structure",
  epigenomic = "Epigenomic feature",
}

export const nodeDefinitions: NodeDefinition[] = [
  {
    id: "gene",
    name: "Gene",
    category: CATEGORIES.coding,
  },
  {
    id: "protein",
    name: "Protein",
    category: CATEGORIES.coding,
  },
  {
    id: "exon",
    name: "Exon",
    category: CATEGORIES.coding,
  },
  {
    id: "transcript",
    name: "Transcript",
    category: CATEGORIES.coding,
  },
  {
    id: "snp",
    name: "SNP",
    category: CATEGORIES.variant,
  },
  {
    id: "sv",
    name: "Structural variant",
    category: CATEGORIES.variant,
  },
  {
    id: "enhancer",
    name: "Enhancer",
    category: CATEGORIES.noncoding,
  },
  {
    id: "super_enhancer",
    name: "Super enhancer",
    category: CATEGORIES.noncoding,
  },
  {
    id: "promoter",
    name: "Promoter",
    category: CATEGORIES.noncoding,
  },
  {
    id: "non_coding_rna",
    name: "Non-coding RNA",
    category: CATEGORIES.noncoding,
  },
  {
    id: "pathway",
    name: "Reactome",
    category: CATEGORIES.process,
  },
  {
    id: "go",
    name: "GO",
    category: CATEGORIES.ontology,
  },
  {
    id: "uberon",
    name: "Uberon",
    category: CATEGORIES.ontology,
  },
  {
    id: "clo",
    name: "CLO",
    category: CATEGORIES.ontology,
  },
  {
    id: "cl",
    name: "CL",
    category: CATEGORIES.ontology,
  },
  {
    id: "efo",
    name: "EFO",
    category: CATEGORIES.ontology,
  },
  {
    id: "bto",
    name: "BTO",
    category: CATEGORIES.ontology,
  },
  {
    id: "motif",
    name: "Motif",
    category: CATEGORIES.noncoding,
  },
  {
    id: "tfbs",
    name: "TFBS",
    category: CATEGORIES.noncoding,
  },
  {
    id: "tad",
    name: "TAD",
    category: CATEGORIES.threeD,
  },
];

export const edgeDefinitions: EdgeDefinition[] = [
  {
    id: "1",
    source: "snp",
    label: "activity_by_contact",
    target: "gene",
  },
  {
    id: "2",
    source: "uberon",
    label: "subclass_of",
    target: "uberon",
  },
  {
    id: "3",
    source: "super_enhancer",
    label: "associated_with",
    target: "gene",
  },
  {
    id: "4",
    source: "enhancer",
    label: "associated_with",
    target: "gene",
  },
  {
    id: "5",
    source: "transcript",
    label: "transcribed_from",
    target: "gene",
  },
  {
    id: "6",
    source: "gene",
    label: "transcribed_to",
    target: "transcript",
  },
  {
    id: "7",
    source: "transcript",
    label: "translates_to",
    target: "protein",
  },
  {
    id: "8",
    source: "protein",
    label: "translation_of",
    target: "transcript",
  },
  {
    id: "9",
    source: "pathway",
    label: "child_pathway_of",
    target: "pathway",
  },
  {
    id: "10",
    source: "gene",
    label: "genes_pathways",
    target: "pathway",
  },
  {
    id: "11",
    source: "pathway",
    label: "parent_pathway_of",
    target: "pathway",
  },
  {
    id: "12",
    source: "bto",
    label: "subclass_of",
    target: "bto",
  },
  {
    id: "13",
    source: "go",
    label: "subclass_of",
    target: "go",
  },
  {
    id: "14",
    source: "efo",
    label: "subclass_of",
    target: "efo",
  },
  {
    id: "15",
    source: "clo",
    label: "subclass_of",
    target: "clo",
  },
  {
    id: "16",
    source: "cl",
    label: "part_of",
    target: "uberon",
  },
  {
    id: "17",
    source: "cl",
    label: "capable_of",
    target: "go",
  },
  {
    id: "18",
    source: "gene",
    label: "expressed_in",
    target: "cl",
  },
  {
    id: "19",
    source: "gene",
    label: "expressed_in",
    target: "uberon",
  },
  {
    id: "20",
    source: "gene",
    label: "binds_to",
    target: "tfbs",
  },
  {
    id: "21",
    source: "promoter",
    label: "associated_with",
    target: "gene",
  },
  {
    id: "22",
    source: "snp",
    label: "eqtl_association",
    target: "gene",
  },
  {
    id: "23",
    source: "snp",
    label: "closest_gene",
    target: "gene",
  },
  {
    id: "24",
    source: "gene",
    label: "regulates",
    target: "gene",
  },
  {
    id: "25",
    source: "gene",
    label: "in_tad_region",
    target: "tad",
  },
  {
    id: "26",
    source: "cl",
    label: "subclass_of",
    target: "cl",
  },
  {
    id: "27",
    source: "non_coding_rna",
    label: "belongs_to",
    target: "go",
  },
  {
    id: "28",
    source: "protein",
    label: "interacts_with",
    target: "protein",
  },
  {
    id: "29",
    source: "snp",
    label: "in_dnase_i_hotspot",
    target: "uberon",
  },
  {
    id: "30",
    source: "snp",
    label: "chromatin_state",
    target: "uberon",
  },
  {
    id: "31",
    source: "snp",
    label: "histone_modification",
    target: "uberon",
  },
  {
    id: "32",
    source: "go",
    label: "go_gene_product",
    target: "protein",
  },
  {
    id: "33",
    source: "gene",
    label: "tfbs_snp",
    target: "snp",
  },
  {
    id: "34",
    source: "gene",
    label: "expressed_in",
    target: "clo",
  },
  {
    id: "35",
    source: "gene",
    label: "expressed_in",
    target: "efo",
  },
  {
    id: "36",
    source: "transcript",
    label: "includes",
    target: "exon",
  },
  {
    id: "37",
    source: "snp",
    label: "chromatin_state",
    target: "cl",
  },
  {
    id: "38",
    source: "snp",
    label: "chromatin_state",
    target: "clo",
  },
  {
    id: "39",
    source: "snp",
    label: "chromatin_state",
    target: "efo",
  },
  {
    id: "40",
    source: "snp",
    label: "in_dnase_i_hotspot",
    target: "cl",
  },
  {
    id: "41",
    source: "snp",
    label: "in_dnase_i_hotspot",
    target: "clo",
  },
  {
    id: "42",
    source: "snp",
    label: "in_dnase_i_hotspot",
    target: "efo",
  },
  {
    id: "43",
    source: "snp",
    label: "histone_modification",
    target: "cl",
  },
  {
    id: "44",
    source: "snp",
    label: "histone_modification",
    target: "clo",
  },
];
